version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8000:5000
  expose:
   - '3306'
  volumes:
  - ./:/clothingStore

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=Lumia@578
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: