# Generated by Django 3.2.17 on 2023-02-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0002_alter_product_bar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bar_code_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
