# Generated by Django 3.2.17 on 2023-02-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_product_bar_code_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
