# Generated by Django 3.2.17 on 2023-02-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_alter_product_bar_code_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='reference_code',
        ),
    ]
